### ISSUE TITLE
FeatureCollection brings "Invalid GeoJSON object"

### ISSUE THREAD

**Issue by vlasvlasvlas** [brandonxiang/leaflet.geoJsonFilter#1]
Hi, i have a valid geojson (tested in geojson.io as an OK geojson) with featurecollection, but when i try the "L.geoJsonFilter(scf_arg).addTo(map);" it brings me "Invalid GeoJSON object"

geojson example:

`{"type":"FeatureCollection","features":[{"geometry": {"type": "Point", "coordinates": [-60.6897988915,-32.9037267678]}, "type": "Feature", "id": 0, "properties": {"Nombre": "Contenedor mal ubicado","DescripciÃ³n": "El contenedor de basura se encuentra a 8 metros de la esquina. A 3 metros de la parada de colectivos. Se debe dejar 30 metros libres cuando existen paradas de colectivo pero no lo cumplen. Entorpece enormemente la visual, acceso-descenso y la circulacion de la arteria. Ya reclame pero no pasa nada. Reclamo 15673-2014","DirecciÃ³n": "Bv. Rondeau 1101-1129 Rosario, Santa Fe, Argentina","image_full": "","URL": "Acceder"}},{"geometry": {"type": "Point", "coordinates": [-60.6870549917,-32.9032178276]}, "type": "Feature", "id": 0, "properties": {"Nombre": "Alcantarilla tapada","DescripciÃ³n": "Siempre que llueve o lavan el auto, la alcantarilla NO absorve el agua. Reiteradas veces realice reclamos en la municipalidad pero no lo arreglan. Reclamos15451-2011, 15613-2011, 44808-2011, 14403-2013. Ponen que esta resuelto pero no lo arreglan.","DirecciÃ³n": "JosÃ© C. Paz 1100-1198 Rosario, Santa Fe, Argentina","image_full": "","URL": "Acceder"}},{"geometry": {"type": "Point", "coordinates": [-60.6839194894,-32.9025715144]}, "type": "Feature", "id": 0, "properties": {"Nombre": "Problema Pavimento","DescripciÃ³n": "La junta del pavimento es inexistente y como consecuencia se produce un lomo de burro no contemplado. Para colmo esta casi en una interseccion donde el derecho de paso lo tiene la misma arteria y luego viene la bajada de la calle Maciel.","DirecciÃ³n": "Maciel 220 S2005NLD Rosario, Santa Fe, Argentina","image_full": "","URL": "Acceder"}},{"geometry": {"type": "Point", "coordinates": [-60.687481463,-32.9020738275]}, "type": "Feature", "id": 0, "properties": {"Nombre": "Rotura pavimento","DescripciÃ³n": "Rotura en la junta del pavimento","DirecciÃ³n": "JosÃ© C. Paz 1100-1198 Rosario, Santa Fe, Argentina","image_full": "","URL": "Acceder"}}]}`

but then again:

`L.geoJsonFilter(scf_arg).addTo(map);` --> `Invalid GeoJSON object`

**Comment by brandonxiang** [comment]
I tried to use your geojson data by my demo in ‘example’ file. I had no problem with my leaflet plugins.

![qq 20160410163702](https://cloud.githubusercontent.com/assets/12969424/14408927/72ea7c82-ff3a-11e5-8546-d676961243a2.jpg)

Which version of leaflet.js did you use?

```
    <link href="//cdn.bootcss.com/leaflet/0.7.7/leaflet.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/leaflet/0.7.7/leaflet.js"></script>
    <script type="text/javascript" src="L.geoJsonFilter.js"></script>
```

**Comment by vlasvlasvlas** [comment]
That made it. i was loading a previous leaflet version.

thankS!!!
